# Generated by Django 3.1 on 2020-08-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hueca',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hueca',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
